package auth

import (
	"crypto/rand"
	"encoding/hex"
	"strings"
	"testing"

	"golang.org/x/crypto/scrypt"
)

func TestHashPassword_AdaptiveFormat(t *testing.T) {
	hash, err := HashPassword("testpassword123")
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	// New format: scrypt$<N>$<salt>$<key> → 4 parts
	parts := strings.SplitN(hash, "$", 4)
	if len(parts) != 4 {
		t.Fatalf("hash should have 4 parts separated by $, got %d", len(parts))
	}

	if parts[0] != "scrypt" {
		t.Errorf("hash should start with 'scrypt', got: %s", parts[0])
	}

	if parts[1] != "32768" {
		t.Errorf("N parameter should be 32768, got: %s", parts[1])
	}

	// Salt should be 32 hex chars (16 bytes)
	if len(parts[2]) != 32 {
		t.Errorf("salt hex should be 32 chars, got %d", len(parts[2]))
	}

	// Key should be 128 hex chars (64 bytes)
	if len(parts[3]) != 128 {
		t.Errorf("key hex should be 128 chars, got %d", len(parts[3]))
	}
}

func TestHashPassword_Unique(t *testing.T) {
	hash1, _ := HashPassword("same_password")
	hash2, _ := HashPassword("same_password")

	if hash1 == hash2 {
		t.Error("two hashes of the same password should differ (random salt)")
	}
}

func TestComparePassword_AdaptiveFormat(t *testing.T) {
	password := "enterprise_grade_password"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	match, err := ComparePassword(password, hash)
	if err != nil {
		t.Fatalf("ComparePassword failed: %v", err)
	}
	if !match {
		t.Error("password should match its own hash (adaptive format)")
	}
}

func TestComparePassword_LegacyFormat(t *testing.T) {
	// Simulate a hash generated by Node.js: scrypt$<salt>$<key> with N=16384
	password := "legacy_node_password"
	salt := make([]byte, saltLen)
	if _, err := rand.Read(salt); err != nil {
		t.Fatalf("salt generation failed: %v", err)
	}

	key, err := scrypt.Key([]byte(password), salt, scryptNLegacy, scryptR, scryptP, keyLen)
	if err != nil {
		t.Fatalf("scrypt key derivation failed: %v", err)
	}

	legacyHash := "scrypt$" + hex.EncodeToString(salt) + "$" + hex.EncodeToString(key)

	match, err := ComparePassword(password, legacyHash)
	if err != nil {
		t.Fatalf("ComparePassword failed on legacy hash: %v", err)
	}
	if !match {
		t.Error("legacy Node.js hash should verify correctly with N=16384 fallback")
	}
}

func TestComparePassword_Invalid(t *testing.T) {
	hash, _ := HashPassword("correct_password")

	match, err := ComparePassword("wrong_password", hash)
	if err != nil {
		t.Fatalf("ComparePassword failed: %v", err)
	}
	if match {
		t.Error("wrong password should not match")
	}
}

func TestComparePassword_LegacyBcrypt(t *testing.T) {
	// Legacy bcrypt hash should gracefully return false
	match, err := ComparePassword("password", "$2b$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012")
	if err != nil {
		t.Fatalf("ComparePassword should not error on bcrypt: %v", err)
	}
	if match {
		t.Error("bcrypt hash should return false (unsupported)")
	}
}

func TestComparePassword_MalformedHash(t *testing.T) {
	_, err := ComparePassword("password", "scrypt$invalid")
	if err == nil {
		t.Error("malformed hash should return error")
	}
}

func TestNeedsRehash_LegacyFormat(t *testing.T) {
	// 3-part legacy format always needs rehash
	legacyHash := "scrypt$" + strings.Repeat("ab", 16) + "$" + strings.Repeat("cd", 64)
	if !NeedsRehash(legacyHash) {
		t.Error("legacy 3-part hash should need rehash")
	}
}

func TestNeedsRehash_OutdatedN(t *testing.T) {
	// 4-part format with old N=16384 needs rehash
	oldHash := "scrypt$16384$" + strings.Repeat("ab", 16) + "$" + strings.Repeat("cd", 64)
	if !NeedsRehash(oldHash) {
		t.Error("hash with N=16384 should need rehash to N=32768")
	}
}

func TestNeedsRehash_CurrentN(t *testing.T) {
	// 4-part format with current N=32768 does NOT need rehash
	hash, _ := HashPassword("current_password")
	if NeedsRehash(hash) {
		t.Error("hash with current N=32768 should NOT need rehash")
	}
}

func TestNeedsRehash_BcryptHash(t *testing.T) {
	if !NeedsRehash("$2b$10$somebcrypthash") {
		t.Error("non-scrypt hash should need rehash")
	}
}

func TestCrossCompatibility_LegacyToAdaptive(t *testing.T) {
	// Verify the full upgrade flow:
	// 1. Legacy hash created by Node.js (N=16384)
	// 2. Go verifies it successfully
	// 3. NeedsRehash detects it
	// 4. Go creates a new adaptive hash (N=32768)
	// 5. New hash is verifiable
	password := "upgrade_test_password"

	// Step 1: Simulate Node.js legacy hash
	salt := make([]byte, saltLen)
	rand.Read(salt)
	key, _ := scrypt.Key([]byte(password), salt, scryptNLegacy, scryptR, scryptP, keyLen)
	legacyHash := "scrypt$" + hex.EncodeToString(salt) + "$" + hex.EncodeToString(key)

	// Step 2: Verify legacy hash
	match, err := ComparePassword(password, legacyHash)
	if err != nil || !match {
		t.Fatal("legacy hash should verify successfully")
	}

	// Step 3: Detect rehash need
	if !NeedsRehash(legacyHash) {
		t.Fatal("legacy hash should need rehash")
	}

	// Step 4: Create new adaptive hash
	newHash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	// Step 5: Verify new hash
	match, err = ComparePassword(password, newHash)
	if err != nil || !match {
		t.Fatal("new adaptive hash should verify successfully")
	}

	// Step 6: New hash should NOT need rehash
	if NeedsRehash(newHash) {
		t.Fatal("new adaptive hash should NOT need rehash")
	}
}
