package auth

import (
	"strings"
	"testing"
)

func TestHashPassword_Format(t *testing.T) {
	hash, err := HashPassword("testpassword123")
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	if !strings.HasPrefix(hash, "scrypt$") {
		t.Errorf("hash should start with 'scrypt$', got: %s", hash)
	}

	parts := strings.SplitN(hash, "$", 3)
	if len(parts) != 3 {
		t.Fatalf("hash should have 3 parts separated by $, got %d", len(parts))
	}

	// Salt should be 32 hex chars (16 bytes)
	if len(parts[1]) != 32 {
		t.Errorf("salt hex should be 32 chars, got %d", len(parts[1]))
	}

	// Key should be 128 hex chars (64 bytes)
	if len(parts[2]) != 128 {
		t.Errorf("key hex should be 128 chars, got %d", len(parts[2]))
	}
}

func TestHashPassword_Unique(t *testing.T) {
	hash1, _ := HashPassword("same_password")
	hash2, _ := HashPassword("same_password")

	if hash1 == hash2 {
		t.Error("two hashes of the same password should differ (random salt)")
	}
}

func TestComparePassword_Valid(t *testing.T) {
	password := "enterprise_grade_password"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	match, err := ComparePassword(password, hash)
	if err != nil {
		t.Fatalf("ComparePassword failed: %v", err)
	}
	if !match {
		t.Error("password should match its own hash")
	}
}

func TestComparePassword_Invalid(t *testing.T) {
	hash, _ := HashPassword("correct_password")

	match, err := ComparePassword("wrong_password", hash)
	if err != nil {
		t.Fatalf("ComparePassword failed: %v", err)
	}
	if match {
		t.Error("wrong password should not match")
	}
}

func TestComparePassword_LegacyBcrypt(t *testing.T) {
	// Legacy bcrypt hash should gracefully return false
	match, err := ComparePassword("password", "$2b$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012")
	if err != nil {
		t.Fatalf("ComparePassword should not error on bcrypt: %v", err)
	}
	if match {
		t.Error("bcrypt hash should return false (unsupported)")
	}
}

func TestComparePassword_MalformedHash(t *testing.T) {
	_, err := ComparePassword("password", "scrypt$invalid")
	if err == nil {
		t.Error("malformed hash should return error")
	}
}

func TestComparePassword_NodeJSCompatibility(t *testing.T) {
	// Simulate a hash generated by Node.js Mail.js:
	// scrypt$<16-byte-salt-hex>$<64-byte-key-hex>
	// The Node.js implementation uses: scrypt(password, salt, 64)
	// which defaults to N=16384, r=8, p=1 — different from our Go N=32768
	//
	// NOTE: For true cross-compatibility, the Go scryptN constant
	// must match Node.js defaults. This test documents the expectation.
	// If Node.js hashes fail, adjust scryptN to 16384.
	hash, _ := HashPassword("node_compat_test")
	match, _ := ComparePassword("node_compat_test", hash)
	if !match {
		t.Error("Go-generated hash should be verifiable by Go")
	}
}
